FROM elixir:1.14 as base

RUN apt-get update && apt-get install -y libcap-dev locales iptables ipset lsb-release jq curl make

RUN mix local.hex --force && mix local.rebar --force

WORKDIR /app

COPY . /app

COPY config/default.exs /etc/dog_ex/env_config.exs

RUN mix deps.get \
    # Needed to remove tertiary beams with wrong OTP version
    && mix deps.clean --all --build \
    && mix compile \
    && mix release --path dog_agent_ex

CMD ["/bin/bash"]
