FROM elixir:1.14 as base

RUN apt-get update && apt-get install -y libcap-dev locales iptables ipset lsb-release jq curl make

RUN mix local.hex --force && mix local.rebar --force

WORKDIR /app

COPY . /app

RUN mkdir /etc/dog_ex

ARG dog_env
RUN echo "The dog_env variable value is ${dog_env}"

COPY config/runtime.${dog_env}.exs config/runtime.exs

RUN mix deps.get \
    # Needed to remove tertiary beams with wrong OTP version
    && mix deps.clean --all --build \
    && mix compile \
    && MIX_ENV=${dog_env} mix release --path dog_agent_ex

CMD ["/bin/bash"]
