# Generated by erl2ex (http://github.com/dazuma/erl2ex)
# From Erlang source: (Unknown source file)
# At: 2022-12-26 15:52:18


defmodule :dog_os do

  # Begin included file: dog.hrl


  defmacrop erlconst_IPsExchange() do
    quote do
      "ips"
    end
  end


  defmacrop erlconst_IptablesExchange() do
    quote do
      "iptables"
    end
  end


  defmacrop erlconst_ConfigExchange() do
    quote do
      "config"
    end
  end


  defmacrop erlconst_RUNDIR() do
    quote do
      '/etc/dog'
    end
  end


  defmacrop erlconst_CONFIG_FILE() do
    quote do
      '/etc/dog/config.json'
    end
  end


  defmacrop erlconst_LOCAL_CONFIG_FILE() do
    quote do
      '/etc/dog/local_config.json'
    end
  end


  defmacrop erlconst_SERVER() do
    quote do
      __MODULE__
    end
  end


  defmacrop erlmacro_CMD(s) do
    quote do
      :dog_os.cmd(unquote(s))
    end
  end


  defmacrop erlconst_PID_FILE() do
    quote do
      '/var/run/dog/dog.pid'
    end
  end


  defmacrop erlconst_EC2_METADATA_BASE_URL() do
    quote do
      'http://169.254.169.254'
    end
  end


  # End included file: dog.hrl


  def cmd(var_cmd) do
    :os.cmd(var_cmd)
  end

end
