# Generated by erl2ex (http://github.com/dazuma/erl2ex)
# From Erlang source: (Unknown source file)
# At: 2022-12-26 15:52:18


defmodule :dog_os do
  require Logger

  def cmd(var_cmd) do
    :os.cmd(var_cmd)
  end

end
