# Generated by erl2ex (http://github.com/dazuma/erl2ex)
# From Erlang source: (Unknown source file)
# At: 2022-12-26 15:52:14


defmodule :dog_app do

  @behaviour :application


  def start(_startType, _startArgs) do
    :dog_sup.start_link()
  end


  def stop(_state) do
    :ok
  end


  @spec get_version() :: {:ok, binary()}


  def get_version() do
    {:ok, version} = :application.get_env(:dog, :version)
    {:ok, :binary.list_to_bin(version)}
  end

end
