# Generated by erl2ex (http://github.com/dazuma/erl2ex)
# From Erlang source: (Unknown source file)
# At: 2022-12-26 15:52:18


defmodule :dog_string do

  @spec split(char_list(), char_list()) :: list()


  def split(string, delimiter, :all) do
    :string.split(string, delimiter, :all)
  end


  def split(string, delimiter) do
    :string.split(string, delimiter)
  end


  @spec trim(char_list(), :trailing, char_list()) :: list()


  def trim(string, :trailing, ' ') do
    :string.trim(string, :trailing, ' ')
  end


  def replace(string, searchPattern, replacement, :all) do
    replaced = :re.replace(string, searchPattern, replacement, [:global, {:return, :list}])
    [replaced]
  end

end
